### PR TITLE
fix: double render in studio mode

### LINKED ISSUE #591: (Studio) Double connect view
“Double connect view” where the document editor shows on the top half of the page and at the bottom the drive explorer still shows (which can be seen scrolling down)

### PR DESCRIPTION
**Pull request by acaldas**
Fixes #591

### CODE REVIEW

File: src/renderer.ts [hunk 1]
```diff
@@ -25,22 +25,6 @@
  *  });
  * ```
  */
-import { createRoot } from 'react-dom/client';
-import App from './components/app';
-import './i18n';
```
Comment (acaldas) [inline src/renderer.ts:30]: The extra work that was being done here was making it so that things like the i18n code was bundled together with the app initialization code (createRoot) and creating a cyclical dependency.

In Studio mode, Vite was importing the main chunk twice, first because is is imported on `index.html`and again when it was imported by another chunk as it added a `?v=xxxx`, making the browser treat it as a different chunk,

Doing a dynamic import forces vite to create a separate chunk.

**Review by gpuente — APPROVED** [review]
